apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  labels:
    app: api-config
data:
  DATABASE_URL: postgresql://loja-user:loja123@db-service:5432/loja
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
