version: "3.7"

services: 
    api:
        build: ./Api
        restart: always
        command: gunicorn --bind 0.0.0.0:5000 api
        volumes: 
            - ./Api:/usr/src/api
        expose: 
            - 5000
        env_file: ./.env.dev
        
        depends_on: 
            - db
    
    db:
        image: postgres:9.6
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=loja
            - POSTGRES_PASSWORD=loja
            - POSTGRES_DATABASE=loja
    nginx:
        build: ./nginx
        ports: 
            - 80:80
volumes: 
    postgres_data:

    