version: "3.7"

services: 
    api:
        build: ./Api
        restart: always
        command: python app.py run -h 0.0.0.0
        volumes: 
            - ./Api:/usr/src/api
        ports: 
            - 5000:5000
        env_file: ./.env.dev
        
        depends_on: 
            - db
        
        networks: 
            - database
            - net

    
    db:
        image: postgres:9.6
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=loja
            - POSTGRES_PASSWORD=loja
            - POSTGRES_DATABASE=loja
        networks: 
            - database

volumes: 
    postgres_data:

networks: 
    database:
    net:


    