version: "3.7"

services: 
    api:
        build: ./Api
        restart: always
        command: gunicorn --workers=2 --threads=4 --worker-class=gthread --bind 0.0.0.0:5000 app:app
        volumes: 
            - ./Api:/usr/src/api
        expose: 
            - 5000
        # ports: 
        #     - 80:5000
        env_file: ./.env.dev.prod
        
        depends_on: 
            - db
        
        networks: 
            - database
            - net

    
    db:
        image: postgres:9.6
        volumes: 
            - postgres_data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=loja
            - POSTGRES_PASSWORD=loja
            - POSTGRES_DATABASE=loja
        networks: 
            - database

    nginx:
        build: ./nginx
        ports: 
            - 80:80
        depends_on: 
            - api
        networks: 
            - net
volumes: 
    postgres_data:

networks: 
    database:
    net:


    