---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 5000
  selector:
    app: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: rspandre/ar-dev:0.1.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 5000
              protocol: TCP
              name: api-port
          envFrom:
            - configMapRef:
                name: api
          volumeMounts:
            - mountPath: /usr/src/api/static/images
              name: api-volume
      volumes:
        - name: api-volume
          persistentVolumeClaim:
            claimName: api-pvc
