"""empty message

Revision ID: 6a42ff12045e
Revises: fb6ccf45b3e9
Create Date: 2020-09-17 01:29:24.517046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a42ff12045e'
down_revision = 'fb6ccf45b3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id_product', sa.Integer(), nullable=False))
    op.drop_column('product', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('product', 'id_product')
    # ### end Alembic commands ###
