"""empty message

Revision ID: fb6ccf45b3e9
Revises: f2e6c0ee3b47
Create Date: 2020-09-17 01:26:45.211166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6ccf45b3e9'
down_revision = 'f2e6c0ee3b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('category', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('product', sa.Column('maximum_stock', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('minimum_stock', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('obs', sa.String(length=120), nullable=True))
    op.add_column('product', sa.Column('sale_price', sa.Float(precision=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'sale_price')
    op.drop_column('product', 'obs')
    op.drop_column('product', 'minimum_stock')
    op.drop_column('product', 'maximum_stock')
    op.drop_column('product', 'description')
    op.drop_column('product', 'category')
    op.drop_column('product', 'brand')
    # ### end Alembic commands ###
